base_dir: "/lustre/scratch119/casm/team163gv/vm11/GONIA/2020.03.Gonia.Dnmt3aR882H.ATACSeq/align"
sample_file: "/lustre/scratch119/casm/team163gv/vm11/GONIA/2020.03.Gonia.Dnmt3aR882H.ATACSeq/align/samples.csv"
genome: "mm10"
