jobs: 999
cluster: "bsub -M {resources.memory} -R \"select[mem>{resources.memory}] rusage[mem={resources.memory}] span[hosts={resources.cpus}]\" -o logs/{rule}.{wildcards}.cluster -e logs/{rule}.{wildcards}.cluster -J {rule}.{wildcards} -q normal -n {resources.cores} "
use-singularity: true
use-conda: true
default-resources: [memory=8000, cpus=1, cores=1] 
