jobs: 999
cluster: "bsub -M {resources.mem_mb} -R \"select[mem>{resources.mem_mb}] rusage[mem={resources.mem_mb}] span[hosts={resources.cpus}]\" -o logs/{rule}.{wildcards}.cluster -e logs/{rule}.{wildcards}.cluster -J {rule}.{wildcards} -q normal -n {threads} "
use-singularity: true
use-conda: true
default-resources: [mem_mb=8000, cpus=1, cores=1] 
