jobs: 999
cluster: "bsub -M {resource.memory} -R \"select[mem>resource.memory] rusage[mem=resource.memory] span[hosts=resource.nhosts]\" -o {rule}.{wildcards.sample}.cluster -e {rule}.{wildcards.sample}.cluster -J {rule}.{wildcards.sample} -q normal -n {resource.cores} "
use-singularity: true
use-conda: true
default-resources: [memory=200, cpus=1, threads=1, resource.cores=1] 
