jobs: 999
cluster: "bsub -M {resources.mem_mb} -R \"select[mem>{resources.mem_mb}] rusage[mem={resources.mem_mb}] span[hosts={resources.cpus}]\" -oo logs/{rule}.{wildcards}.cluster -eo logs/{rule}.{wildcards}.cluster -J {rule}.{wildcards} -q normal -n {resources.cores} "
use-singularity: true
use-conda: true
# default-resources: [mem_mb=8000, cpus=1, cores=1] 

# In the individual rule files use following:
#  resources:
#       mem_mb=lambda wildcards, attempt: attempt * 8000,
#        cpus=1, # Total cpus to use
#        cores=2 # Cores/cpu to use
#  threads: 2

